import bcrypt from 'bcryptjs';
import { prisma } from '../config/db.js';
import { userSchema,storeSchema } from '../validators/index.js';
const safe=u=>({id:u.id,name:u.name,email:u.email,address:u.address,role:u.role});
const pagination=req=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Math.max(1,Number(req.query.limit)||10));return {page,limit,skip:(page-1)*limit};};
export async function dashboard(req,res){const [users,stores,ratings]=await Promise.all([prisma.user.count(),prisma.store.count(),prisma.rating.count()]);res.json({totalUsers:users,totalStores:stores,totalRatings:ratings});}
export async function createUser(req,res){const data=userSchema.parse(req.body);const role=['USER','STORE_OWNER','ADMIN'].includes(req.body.role)?req.body.role:'USER';const user=await prisma.user.create({data:{name:data.name,email:data.email,address:data.address,passwordHash:await bcrypt.hash(data.password,10),role}});res.status(201).json({user:safe(user)});}
export async function listUsers(req,res){const {page,limit,skip}=pagination(req);const {name,email,address,role,sortBy='name',sortOrder='asc'}=req.query;const where={};if(name)where.name={contains:String(name),mode:'insensitive'};if(email)where.email={contains:String(email),mode:'insensitive'};if(address)where.address={contains:String(address),mode:'insensitive'};if(['USER','ADMIN','STORE_OWNER'].includes(role))where.role=role;const allowed=['name','email','address','role','createdAt'];const orderBy={[allowed.includes(sortBy)?sortBy:'name']:sortOrder==='desc'?'desc':'asc'};const [rows,total]=await Promise.all([prisma.user.findMany({where,skip,take:limit,orderBy}),prisma.user.count({where})]);res.json({data:rows.map(safe),pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}});}
export async function getUser(req,res){const u=await prisma.user.findUnique({where:{id:Number(req.params.id)},include:{ownedStores:{include:{ratings:true}},ratings:true}});if(!u)return res.status(404).json({message:'User not found'});res.json({user:{...safe(u),storeRatings:u.ownedStores.map(s=>({storeId:s.id,storeName:s.name,averageRating:s.ratings.length?s.ratings.reduce((a,r)=>a+r.rating,0)/s.ratings.length:0}))}});}
export async function createStore(req,res){const data=storeSchema.parse(req.body);const owner=await prisma.user.findUnique({where:{id:data.ownerId}});if(!owner||owner.role!=='STORE_OWNER')return res.status(400).json({message:'ownerId must belong to a Store Owner'});const store=await prisma.store.create({data,include:{owner:{select:{id:true,name:true,email:true}}}});res.status(201).json({store});}
export async function listStores(req,res){const {page,limit,skip}=pagination(req);const {name,email,address,sortBy='name',sortOrder='asc'}=req.query;const where={};if(name)where.name={contains:String(name),mode:'insensitive'};if(email)where.email={contains:String(email),mode:'insensitive'};if(address)where.address={contains:String(address),mode:'insensitive'};const allowed=['name','email','address','createdAt'];const orderBy={[allowed.includes(sortBy)?sortBy:'name']:sortOrder==='desc'?'desc':'asc'};const [rows,total]=await Promise.all([prisma.store.findMany({where,skip,take:limit,orderBy,include:{ratings:true}}),prisma.store.count({where})]);const data=rows.map(s=>({...s,averageRating:s.ratings.length?s.ratings.reduce((a,r)=>a+r.rating,0)/s.ratings.length:0,ratings:undefined}));res.json({data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}});}
